// <auto-generated />
using System;
using LT.SO.Infra.Data.Log.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LT.SO.Infra.Data.Log.Migrations
{
    [DbContext(typeof(LogContext))]
    [Migration("20180929220441_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LT.SO.Infra.CrossCutting.Log.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Controller");

                    b.Property<string>("Cookies");

                    b.Property<DateTime?>("Data");

                    b.Property<string>("Detail");

                    b.Property<string>("Hostname");

                    b.Property<string>("Identifier");

                    b.Property<string>("Message");

                    b.Property<string>("Method");

                    b.Property<string>("ServerVariables");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusCode");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("LogAuditoria");
                });

            modelBuilder.Entity("LT.SO.Infra.CrossCutting.Log.Entities.LogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Application");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnName("Data");

                    b.Property<string>("Detail");

                    b.Property<string>("Hostname");

                    b.Property<string>("LogCookies");

                    b.Property<string>("LogDatas");

                    b.Property<string>("LogForms");

                    b.Property<string>("LogQueryStrings");

                    b.Property<string>("LogServerVariables");

                    b.Property<string>("Method");

                    b.Property<string>("Severity");

                    b.Property<string>("Source");

                    b.Property<int?>("StatusCode");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.Property<string>("User");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("LogErro");
                });
#pragma warning restore 612, 618
        }
    }
}
